CREATE TABLE cards (
    card_id VARCHAR(64) PRIMARY KEY,
    card_name VARCHAR(100) NOT NULL,
    rarity SMALLINT NOT NULL CHECK (rarity BETWEEN 1 AND 4),
    race SMALLINT NOT NULL CHECK (race BETWEEN 1 AND 5),
    base_config JSONB NOT NULL DEFAULT '{}'::jsonb,
    skill_config JSONB NOT NULL DEFAULT '{}'::jsonb,
    is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);